#!/usr/bin/env bash
# Create a simulation-only project scaffold.
# Usage: create_sim_project.sh <project_name>
# Normally invoked by ../initiate_proj.sh, but can be run directly.

set -euo pipefail

readonly GREEN='\033[0;32m'
readonly RED='\033[0;31m'
readonly NC='\033[0m'
log_info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SCRIPT_DIR
readonly TOOLKIT_ROOT="$(dirname "$SCRIPT_DIR")"
readonly TEMPLATES="$TOOLKIT_ROOT/templates"

NAME="${1:-}"
if [[ -z "$NAME" ]]; then
    log_error "No project name given."
    echo "Usage: $0 <project_name>"
    exit 1
fi
if [[ ! "$NAME" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]]; then
    log_error "Invalid project name: '$NAME'"
    echo "Use a Verilog-identifier-safe name: letters, digits, underscore; no leading digit."
    exit 1
fi
if [[ -e "$NAME" ]]; then
    log_error "'$NAME' already exists in $(pwd). Choose another name."
    exit 1
fi

log_info "Creating simulation project: $NAME"

mkdir -p "$NAME/rtl/lib" "$NAME/tb" "$NAME/sim/waves"

# Standard library modules - ready to use, no setup.
cp "$TEMPLATES"/lib/*.v "$NAME/rtl/lib/"

# Example design + self-checking testbench.
sed "s/__DESIGN_NAME__/$NAME/g" "$TEMPLATES/design_stub.v"     > "$NAME/rtl/$NAME.v"
sed "s/__DESIGN_NAME__/$NAME/g" "$TEMPLATES/testbench_stub.v"  > "$NAME/tb/${NAME}_tb.v"

# Makefile.
sed "s/__DESIGN_NAME__/$NAME/g" "$TEMPLATES/Makefile.sim" > "$NAME/Makefile"

# Keep empty waveform dir under version control.
touch "$NAME/sim/waves/.gitkeep"

cat > "$NAME/.gitignore" << 'EOF'
# Simulation outputs
sim/*.vvp
sim/waves/*.vcd
sim/waves/*.fst
EOF

cat > "$NAME/README.md" << EOF
# $NAME

Simulation-only ASIC project, generated by the ASIC Design Toolkit.

## Get going

1. Put your RTL in \`rtl/\` (replace the \`$NAME.v\` stub).
2. Edit the testbench in \`tb/${NAME}_tb.v\`.
3. Run it:

   \`\`\`bash
   make sim-waves
   \`\`\`

Run \`make help\` to see every command.

## Layout

\`\`\`
$NAME/
├── rtl/              your Verilog goes here
│   ├── $NAME.v       example design stub - replace it
│   └── lib/          standard modules, ready to use
├── tb/               testbenches
│   └── ${NAME}_tb.v  example self-checking testbench
├── sim/waves/        VCD output + GTKWave session files
└── Makefile
\`\`\`

The \`rtl/lib/\` modules (synchronizer, edge detector, reset synchronizer,
async FIFO) are picked up automatically by \`make sim\` - instantiate them
whenever you need them.
EOF

log_info "Done. Next:"
echo "  cd $NAME"
echo "  make sim-waves"
