#!/usr/bin/env bash
# Create a Sky130 project scaffold (simulation + OpenLane 2 RTL-to-GDSII).
# Usage: create_sky130_project.sh <project_name>
# Normally invoked by ../initiate_proj.sh, but can be run directly.

set -euo pipefail

readonly GREEN='\033[0;32m'
readonly RED='\033[0;31m'
readonly NC='\033[0m'
log_info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SCRIPT_DIR
readonly TOOLKIT_ROOT="$(dirname "$SCRIPT_DIR")"
readonly TEMPLATES="$TOOLKIT_ROOT/templates"

NAME="${1:-}"
if [[ -z "$NAME" ]]; then
    log_error "No project name given."
    echo "Usage: $0 <project_name>"
    exit 1
fi
if [[ ! "$NAME" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]]; then
    log_error "Invalid project name: '$NAME'"
    echo "Use a Verilog-identifier-safe name: letters, digits, underscore; no leading digit."
    exit 1
fi
if [[ -e "$NAME" ]]; then
    log_error "'$NAME' already exists in $(pwd). Choose another name."
    exit 1
fi

log_info "Creating Sky130 project: $NAME"

mkdir -p "$NAME/rtl/lib" "$NAME/tb" "$NAME/sim/waves" "$NAME/config"

# Standard library modules - ready to use, no setup.
cp "$TEMPLATES"/lib/*.v "$NAME/rtl/lib/"

# Example design + self-checking testbench.
sed "s/__DESIGN_NAME__/$NAME/g" "$TEMPLATES/design_stub.v"    > "$NAME/rtl/$NAME.v"
sed "s/__DESIGN_NAME__/$NAME/g" "$TEMPLATES/testbench_stub.v" > "$NAME/tb/${NAME}_tb.v"

# OpenLane 2 config - newcomer only needs to tweak CLOCK_PERIOD / DIE_AREA.
sed "s/__DESIGN_NAME__/$NAME/g" "$TEMPLATES/config.json" > "$NAME/config/config.json"

# Makefile.
sed "s/__DESIGN_NAME__/$NAME/g" "$TEMPLATES/Makefile.sky130" > "$NAME/Makefile"

# Keep empty waveform dir under version control.
touch "$NAME/sim/waves/.gitkeep"

cat > "$NAME/.gitignore" << 'EOF'
# Simulation outputs
sim/*.vvp
sim/waves/*.vcd
sim/waves/*.fst

# OpenLane 2 output
runs/
EOF

cat > "$NAME/README.md" << EOF
# $NAME

Sky130 ASIC project, generated by the ASIC Design Toolkit.
Simulate your RTL, then take it all the way to GDSII with OpenLane 2.

## Get going

1. Put your RTL in \`rtl/\` (replace the \`$NAME.v\` stub).
2. Edit the testbench in \`tb/${NAME}_tb.v\` and simulate:

   \`\`\`bash
   make sim-waves
   \`\`\`

3. When the design is ready, synthesize and run the full flow:

   \`\`\`bash
   make synth      # RTL -> netlist
   make gds        # RTL -> GDSII
   make view-gds   # open the layout in KLayout
   \`\`\`

Run \`make help\` to see every command.

## Configuration

\`config/config.json\` is the OpenLane 2 config. It is pre-filled - the fields
you are most likely to change:

| Field          | Meaning                                        |
|----------------|------------------------------------------------|
| \`CLOCK_PORT\`   | Name of your clock input (default \`clk\`)       |
| \`CLOCK_PERIOD\` | Target clock period in ns (default 10.0)       |
| \`DIE_AREA\`     | Die size in um (default \`0 0 200 200\`)         |
| \`FP_CORE_UTIL\` | Core utilization percentage (default 50)       |

## Layout

\`\`\`
$NAME/
├── rtl/              your Verilog goes here
│   ├── $NAME.v       example design stub - replace it
│   └── lib/          standard modules, ready to use
├── tb/               testbenches
│   └── ${NAME}_tb.v  example self-checking testbench
├── sim/waves/        VCD output + GTKWave session files
├── config/
│   └── config.json   OpenLane 2 config
├── runs/             OpenLane 2 output (gitignored, created on first run)
└── Makefile
\`\`\`
EOF

log_info "Done. Next:"
echo "  cd $NAME"
echo "  make sim-waves      # simulate the example design"
echo "  make gds            # full RTL-to-GDSII flow (needs --mode=full tools)"
